const DEFAULT_SITE_CONTACT_EMAIL = 'Hello@PickItUpSeattle.org';

export const SITE_CONTACT_EMAIL =
  process.env.NEXT_PUBLIC_SITE_CONTACT_EMAIL?.trim() || DEFAULT_SITE_CONTACT_EMAIL;

export const SITE_CONTACT_MAILTO = `mailto:${SITE_CONTACT_EMAIL}`;
